-- Migration: Bidirectional Mention System
-- Enables agents to @mention users and other agents in documents
-- 
-- User Flow:
-- 1. User types "@claw analyze this"
-- 2. Agent works and writes "@chris analysis complete. please review."
-- 3. System detects @chris, creates mention record
-- 4. Notification sent to chris
-- 5. Mention rendered as permanent inline badge

-- ============================================
-- 1. Extend mentions table for agent-generated mentions
-- ============================================

-- Track if mention was generated by an agent (vs human)
ALTER TABLE public.mentions 
ADD COLUMN IF NOT EXISTS is_agent_generated BOOLEAN DEFAULT false;

-- Track which agent generated the mention
ALTER TABLE public.mentions 
ADD COLUMN IF NOT EXISTS source_agent_id UUID REFERENCES public.agent_personas(id) ON DELETE SET NULL;

-- Track mention type for filtering
ALTER TABLE public.mentions 
ADD COLUMN IF NOT EXISTS mention_type TEXT DEFAULT 'human_to_human' 
CHECK (mention_type IN ('human_to_human', 'human_to_agent', 'agent_to_human', 'agent_to_agent'));

-- Track resolution status (for @unknownuser handling)
ALTER TABLE public.mentions 
ADD COLUMN IF NOT EXISTS resolution_status TEXT DEFAULT 'resolved' 
CHECK (resolution_status IN ('pending', 'resolved', 'unknown_user', 'unknown_agent'));

-- For agent chaining: track parent mention that triggered this
ALTER TABLE public.mentions 
ADD COLUMN IF NOT EXISTS parent_mention_id UUID REFERENCES public.mentions(id) ON DELETE SET NULL;

-- Context around the mention (the sentence/paragraph)
ALTER TABLE public.mentions 
ADD COLUMN IF NOT EXISTS context_text TEXT;

-- ============================================
-- 2. Create mention_resolutions table for tracking
-- ============================================

CREATE TABLE IF NOT EXISTS public.mention_resolutions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  mention_id UUID REFERENCES public.mentions(id) ON DELETE CASCADE,
  
  -- Raw text that was matched
  raw_text TEXT NOT NULL,
  
  -- What we resolved it to
  resolved_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  resolved_agent_id UUID REFERENCES public.agent_personas(id) ON DELETE SET NULL,
  
  -- Resolution status
  resolution_status TEXT DEFAULT 'pending' 
  CHECK (resolution_status IN ('pending', 'resolved', 'unknown_user', 'unknown_agent')),
  
  -- Error message if resolution failed
  resolution_error TEXT,
  
  created_at TIMESTAMPTZ DEFAULT now(),
  resolved_at TIMESTAMPTZ
);

-- ============================================
-- 3. Create notifications table (Supabase-synced)
-- ============================================

CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  workspace_id UUID REFERENCES public.workspaces(id) ON DELETE CASCADE,
  
  -- Notification type
  type TEXT NOT NULL CHECK (type IN (
    'mention', 'comment', 'share', 'agent-suggestion',
    'doc-edit', 'member-joined', 'role-changed',
    'agent-mentioned-you', 'agent-completed-task'
  )),
  
  -- Message content
  message TEXT NOT NULL,
  
  -- Actor who triggered (can be user or agent)
  actor_id TEXT,
  actor_type TEXT DEFAULT 'user' CHECK (actor_type IN ('user', 'agent')),
  actor_name TEXT,
  actor_avatar TEXT,
  
  -- Context
  document_id UUID REFERENCES public.documents(id) ON DELETE CASCADE,
  mention_id UUID REFERENCES public.mentions(id) ON DELETE SET NULL,
  task_id UUID REFERENCES public.agent_tasks(id) ON DELETE SET NULL,
  link TEXT,
  
  -- State
  read BOOLEAN DEFAULT false,
  archived BOOLEAN DEFAULT false,
  
  -- Metadata
  created_at TIMESTAMPTZ DEFAULT now(),
  read_at TIMESTAMPTZ,
  
  -- Composite unique to prevent duplicates
  UNIQUE (user_id, mention_id, created_at)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread 
  ON public.notifications(user_id) 
  WHERE read = false AND archived = false;

CREATE INDEX IF NOT EXISTS idx_notifications_document 
  ON public.notifications(document_id) 
  WHERE document_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_mention 
  ON public.notifications(mention_id) 
  WHERE mention_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_created_at 
  ON public.notifications(created_at DESC);

-- Enable realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;

-- ============================================
-- 4. Create function to auto-process agent mentions
-- ============================================

CREATE OR REPLACE FUNCTION public.process_agent_mention()
RETURNS TRIGGER AS $$
DECLARE
  v_workspace_id UUID;
  v_document_title TEXT;
  v_mentioned_user_id UUID;
  v_mentioned_agent_id UUID;
BEGIN
  -- Only process agent-generated mentions
  IF NEW.is_agent_generated = false THEN
    RETURN NEW;
  END IF;

  -- Get document info
  SELECT workspace_id, title 
  INTO v_workspace_id, v_document_title
  FROM public.documents 
  WHERE id = NEW.document_id;

  -- Try to resolve target as user
  SELECT u.id INTO v_mentioned_user_id
  FROM auth.users u
  JOIN public.workspace_members wm ON wm.user_id = u.id
  WHERE wm.workspace_id = v_workspace_id
  AND (
    u.raw_user_meta_data->>'full_name' ILIKE NEW.target_id
    OR u.raw_user_meta_data->>'name' ILIKE NEW.target_id
    OR u.email ILIKE NEW.target_id || '@%'
  )
  LIMIT 1;

  -- Try to resolve as agent
  IF v_mentioned_user_id IS NULL THEN
    SELECT id INTO v_mentioned_agent_id
    FROM public.agent_personas
    WHERE workspace_id = v_workspace_id
    AND (agent_id = NEW.target_id OR name ILIKE NEW.target_id)
    LIMIT 1;
  END IF;

  -- Create mention resolution record
  INSERT INTO public.mention_resolutions (
    mention_id,
    raw_text,
    resolved_user_id,
    resolved_agent_id,
    resolution_status,
    resolved_at
  ) VALUES (
    NEW.id,
    NEW.target_id,
    v_mentioned_user_id,
    v_mentioned_agent_id,
    CASE 
      WHEN v_mentioned_user_id IS NOT NULL THEN 'resolved'
      WHEN v_mentioned_agent_id IS NOT NULL THEN 'resolved'
      ELSE 'unknown_user'
    END,
    now()
  );

  -- Create notification for mentioned user
  IF v_mentioned_user_id IS NOT NULL THEN
    INSERT INTO public.notifications (
      user_id,
      workspace_id,
      type,
      message,
      actor_type,
      actor_name,
      document_id,
      mention_id,
      link
    )
    SELECT 
      v_mentioned_user_id,
      v_workspace_id,
      'agent-mentioned-you',
      COALESCE(NEW.context_text, 'mentioned you in a document'),
      'agent',
      ap.name,
      NEW.document_id,
      NEW.id,
      '/knowledge?doc=' || NEW.document_id || '&mention=' || NEW.id
    FROM public.agent_personas ap
    WHERE ap.id = NEW.source_agent_id;
  END IF;

  -- For agent-to-agent mentions, could trigger new task creation here
  IF v_mentioned_agent_id IS NOT NULL THEN
    -- TODO: Create chained agent task
    NULL;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for auto-processing
DROP TRIGGER IF EXISTS trg_process_agent_mention ON public.mentions;
CREATE TRIGGER trg_process_agent_mention
  AFTER INSERT ON public.mentions
  FOR EACH ROW
  EXECUTE FUNCTION public.process_agent_mention();

-- ============================================
-- 5. Update notify_on_mention to handle agent->human
-- ============================================

CREATE OR REPLACE FUNCTION public.notify_on_mention()
RETURNS TRIGGER AS $$
DECLARE
  v_target_user_id UUID;
  v_workspace_id UUID;
  v_document_title TEXT;
  v_actor_name TEXT;
BEGIN
  -- Get workspace and document info
  SELECT d.workspace_id, d.title 
  INTO v_workspace_id, v_document_title
  FROM public.documents d
  WHERE d.id = NEW.document_id;

  -- Handle agent -> human mentions
  IF NEW.is_agent_generated = true AND NEW.target_type = 'user' THEN
    -- Get agent name
    SELECT name INTO v_actor_name
    FROM public.agent_personas
    WHERE id = NEW.source_agent_id;

    -- Notification is handled by process_agent_mention trigger
    RETURN NEW;
  END IF;

  -- Handle human -> human mentions (existing logic)
  IF NEW.target_type = 'user' THEN
    v_target_user_id := NEW.target_id::uuid;
    
    -- Get actor name
    SELECT COALESCE(
      raw_user_meta_data->>'full_name',
      raw_user_meta_data->>'name',
      email
    ) INTO v_actor_name
    FROM auth.users
    WHERE id = NEW.created_by;

    -- Create notification
    INSERT INTO public.notifications (
      user_id,
      workspace_id,
      type,
      message,
      actor_type,
      actor_name,
      document_id,
      mention_id,
      link
    ) VALUES (
      v_target_user_id,
      v_workspace_id,
      'mention',
      'mentioned you in "' || COALESCE(v_document_title, 'Untitled') || '"',
      'user',
      v_actor_name,
      NEW.document_id,
      NEW.id,
      '/knowledge?doc=' || NEW.document_id
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 6. Indexes for performance
-- ============================================

CREATE INDEX IF NOT EXISTS idx_mentions_agent_generated 
  ON public.mentions(is_agent_generated) 
  WHERE is_agent_generated = true;

CREATE INDEX IF NOT EXISTS idx_mentions_source_agent 
  ON public.mentions(source_agent_id) 
  WHERE source_agent_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mentions_type 
  ON public.mentions(mention_type);

CREATE INDEX IF NOT EXISTS idx_mentions_resolution 
  ON public.mentions(resolution_status);

CREATE INDEX IF NOT EXISTS idx_mention_resolutions_status 
  ON public.mention_resolutions(resolution_status);

-- ============================================
-- 7. Comments for documentation
-- ============================================

COMMENT ON COLUMN public.mentions.is_agent_generated IS 'True if this mention was created by an AI agent vs a human user';
COMMENT ON COLUMN public.mentions.source_agent_id IS 'Reference to the agent that generated this mention';
COMMENT ON COLUMN public.mentions.mention_type IS 'Type: human_to_human, human_to_agent, agent_to_human, agent_to_agent';
COMMENT ON COLUMN public.mentions.parent_mention_id IS 'For reply threading - references the mention this is responding to';
COMMENT ON TABLE public.notifications IS 'User notifications synced across devices via Supabase realtime';
COMMENT ON TABLE public.mention_resolutions IS 'Tracks how @mentions were resolved to actual users/agents';
