-- Migration 031: Disable RLS on remaining tables
-- Migration 026 missed several tables that the app queries via the browser
-- client (anon key). Without RLS disabled (and no SELECT policies defined),
-- the browser gets empty results for agent listings, task queues, etc.

ALTER TABLE IF EXISTS public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.schools DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.bots DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.agent_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mentions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.agent_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.agent_edit_proposals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.agent_webhooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.agent_api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.agent_personas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.page_permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.page_blocks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.workspace_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_webhooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.knowledge_packs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pack_purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pack_reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.import_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.organization_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.auth_profiles DISABLE ROW LEVEL SECURITY;
