export {
  createClient,
  type Database,
  type Tables,
  type InsertDto,
  type UpdateDto,
} from "./client";

export {
  createServerClient,
  createAdminClient,
} from "./server";

export type {
  TypedSupabaseClient,
  AuthUser,
  UserProfile,
  Workspace,
  WorkspaceMember,
  Document,
  WorkspaceWithMembers,
  DocumentWithCreator,
  WorkspaceRole,
  CreateWorkspaceInput,
  CreateDocumentInput,
  UpdateDocumentInput,
  UpdateProfileInput,
  AddWorkspaceMemberInput,
  PermissionCheck,
  // Agent coordination types
  AgentTask,
  AgentTaskInsert,
  AgentTaskUpdate,
  AgentTaskStatus,
  AgentTaskType,
  Mention,
  MentionInsert,
  MentionUpdate,
  MentionStatus,
  AgentSession,
  AgentSessionInsert,
  AgentSessionUpdate,
  AgentSessionStatus,
  AgentEditProposal,
  AgentEditProposalInsert,
  AgentEditProposalUpdate,
  EditProposalStatus,
  EditType,
  AgentNotification,
  AgentNotificationInsert,
  DocumentBlock,
  DocumentBlockInsert,
  DocumentBlockUpdate,
  AgentPersonaRow,
  AgentPersonaInsert,
  AgentPersonaUpdate,
} from "./types";
